---
ansible:
  version: 2.9.6

defaults:
  alpine: &alpineDefaults
    versions:
      - 3.10.4
      - 3.11.5
    java:
      enabled: false
    python3:
      enabled: true
  debian: &debianDefaults
    versions:
      - 9
      - 10
    java:
      enabled: false
    python3:
      enabled: true
  ubuntu: &ubuntuDefaults
    versions:
      - 18.04
      - 20.04
    java:
      enabled: false
    python3:
      enabled: true

distros:
  alpine:
    py3:
      template: alpine
      <<: *alpineDefaults
    java:
      template: alpine
      <<: *alpineDefaults
      java:
        enabled: true

  debian:
    py3:
      template: debian
      <<: *debianDefaults
    java:
      template: debian
      <<: *debianDefaults
      java:
        enabled: true

  ubuntu:
    py3:
      template: debian
      <<: *ubuntuDefaults
    java:
      template: debian
      <<: *ubuntuDefaults
      java:
        enabled: true
