---
ansible:
  version: 2.9.6

defaults:
  alpine: &alpineDefaults
    versions:
      - 3.11.5
      - 3.10.4
    java:
      enabled: false
    python3:
      enabled: true
  debian: &debianDefaults
    versions:
      - 8
      - 9
      - 10
    java:
      enabled: false
    python3:
      enabled: true
  ubuntu: &ubuntuDefaults
    versions:
      - 16.04
      - 18.04
    java:
      enabled: false
    python3:
      enabled: true

distros:
  alpine:
    py3:
      template: alpine
      <<: *alpineDefaults
    java:
      template: alpine
      java:
        enabled: true
      <<: *alpineDefaults

  debian:
    py3:
      template: debian
      <<: *debianDefaults
      versions:
        - 9
        - 10
    java:
      template: debian
      java:
        enabled: true
      <<: *debianDefaults

  ubuntu:
    py3:
      template: debian
      <<: *ubuntuDefaults
      versions:
        - 16.04
        - 18.04
        - 20.04
    java:
      template: debian
      <<: *ubuntuDefaults
      java:
        enabled: true
      versions:
        - 16.04
        - 18.04
        - 20.04
