---
ansible:
  version: 6.5.0

defaults:
  alpine: &alpineDefaults
    versions:
      - 3.10.4
      - 3.15.6
      - 3.16.2
    java:
      enabled: false

  debian: &debianDefaults
    versions:
      # - 9
      - 10
      - 11
    java:
      enabled: false

  ubuntu: &ubuntuDefaults
    versions:
      # - "18.04"
      - "20.04"
      - "22.04"
      - "22.10"
    java:
      enabled: false

distros:
  alpine:
    base:
      <<: *alpineDefaults
      template: alpine

    java:
      <<: *alpineDefaults
      template: alpine
      java:
        enabled: true

  debian:
    base:
      <<: *debianDefaults
      template: debian

    java:
      <<: *debianDefaults
      template: debian
      java:
        enabled: true

  ubuntu:
    base:
      <<: *ubuntuDefaults
      template: debian

    java:
      <<: *ubuntuDefaults
      template: debian
      java:
        enabled: true
