{%- extends "base/Dockerfile.jinja2" -%}

{%- block os_packages -%}
RUN apk --update --no-cache add sudo \
        openssl ca-certificates bash \
        tar curl zlib-dev gzip iproute2 \
        libffi-dev openssl-dev make build-base \
{%- if java.enabled %}
        openjdk8-jre-base \
{%- endif %}
        openssh-client rsync sshpass
{%- endblock %}
